### PR TITLE
g45w-lw

### PR DESCRIPTION
**Pull request by ghost**
g45w-lw was made under the premise of a lite weight wallet for western audiences who have limited access to data and storage.

### CODE REVIEW

**Comment by ghost** [comment]
https://explorer.dero.io/tx/b7ab4282b9ef9a680e89936d696844bbda6dc91b0f2b613ac39b712fdb5abaf7

**Comment by ghost** [comment]
https://explorer.dero.io/tx/809bada8c6aa94fddfa7d9c0facd6930cc024e3d72db2e1927dff2eb4412aca8

**Comment by ghost** [comment]
https://explorer.dero.io/tx/4b9698dd3e8d3e17eece34a807c38be35579e100f81e6ecda11fd77274902dfb

**Comment by ghost** [comment]
thank you for making such an awesome wallet.

**Comment by g45t345rt** [comment]
Closing. I understand you were looking for a barebone wallet and did not want to contribute to add/fix things, so there's no need for a pull request. Feel free to go in the direction you prefer with the wallet. I don't mind if you give it your name, remove features, remove languages, etc. Yes, I found it weird initially, but no worries. The only thing that bothered me was you removing the donation page and sharing it with others. That's all. For me, this is something I would never think of doing. I guess to each our own mindset, and I also understand that others can find this trivial.

I can see that you have made a huge donation. Thanks, but come on, I will send it back. I don't want it, even if it's genuine. Sorry if it's not the outcome you're looking for, but I'm not one to forgive someone I barely know. Let's go our separate ways and continue to build/grow for the best of the Dero ecosystem. Godspeed!

**Comment by ghost** [comment]
thanks g

**Pull request closed without merging**
